### ISSUE TITLE
Some thoughts about strain gauges.

### ISSUE THREAD

**Issue by troisiemetype** [ioces/haptick#11]
Hello,

I've just read the article on Hackaday and on your blog, and it brings me two thoughts : 

1. I believe the red-dotted trackpad on Thinkpads uses strain jauges too. I was surprised to see that once you've removed the rubber part and the plastic part beneath it, you're left with rigid metallic component, with zero degrees of freedom.
2. The idea of using resistors for strain gauges is brilliant. I wonder if that could be pushed further, by directly using specifically designed tracks as strain gauges ?

Thank you for this complete writing on your research !

**Comment by m-schubert** [comment]
Thanks for getting in touch @troisiemetype.

1. Yeah, I'm not surprised the Thinkpad [nub](https://xkcd.com/243/) uses strain gauges. It only has 2 degrees of freedom, so you could get away with a pretty simple load cell design to implement it.
2. I considered trying to etch the gauges directly onto the PCB. Actually, the folks at Duet 3D used to use thick film resistors like I did for their [Smart Effector](https://www.duet3d.com/DeltaSmartEffector), but have moved to PCB traces. The problem I see is they're going to be really low impedance. With 17.5 um copper and 0.1 mm traces, I only get several ohms of impedance in the strain sensitive area. That's too low to excite directly with a voltage source and digitise directly with an ADC. I have seen some constantin foil, or direct resistive element on PCB technology that could be worth a shot.

**Comment by troisiemetype** [comment]
I didn't think of the low impedance of the tracks. But another problem may be the tolerances of the PCB manufacturer. I suppose they are far less than on a strain gauge, which may imply a more complex calibration procedure.

**Comment by m-schubert** [comment]
Yeah, generally I see pretty high resolution traces on the foil strain gauges - certainly higher than most PCB manufacturers will hit. It's something I might investigate in the future, but for now I'll begrudgingly glue strain gauges to the PCBs.

I'll close this "issue" as resolved. Thanks again for getting in touch!
